<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrmReferenceDataSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $this->upsert('lead_statuses', [
            ['key' => 'new', 'label' => 'New', 'color' => 'teal', 'is_final' => 0, 'terminal_type' => null, 'is_active' => 1, 'sort_order' => 1, 'requires_datetime' => 0, 'requires_booking_details' => 0],
            ['key' => 'attempted', 'label' => 'Attempted', 'color' => 'blue', 'is_final' => 0, 'terminal_type' => null, 'is_active' => 1, 'sort_order' => 2, 'requires_datetime' => 0, 'requires_booking_details' => 0],
            ['key' => 'contacted', 'label' => 'Contacted', 'color' => 'orange', 'is_final' => 0, 'terminal_type' => null, 'is_active' => 1, 'sort_order' => 3, 'requires_datetime' => 0, 'requires_booking_details' => 0],
            ['key' => 'visit_scheduled', 'label' => 'Visit Scheduled', 'color' => 'purple', 'is_final' => 0, 'terminal_type' => null, 'is_active' => 1, 'sort_order' => 4, 'requires_datetime' => 1, 'requires_booking_details' => 0],
            ['key' => 'visit_done', 'label' => 'Visit Done', 'color' => 'blue', 'is_final' => 0, 'terminal_type' => null, 'is_active' => 1, 'sort_order' => 5, 'requires_datetime' => 0, 'requires_booking_details' => 0],
            ['key' => 'negotiation', 'label' => 'Negotiation', 'color' => 'amber', 'is_final' => 0, 'terminal_type' => null, 'is_active' => 1, 'sort_order' => 6, 'requires_datetime' => 0, 'requires_booking_details' => 0],
            ['key' => 'booking', 'label' => 'Booking', 'color' => 'green', 'is_final' => 1, 'terminal_type' => 'won', 'is_active' => 1, 'sort_order' => 7, 'requires_datetime' => 0, 'requires_booking_details' => 1],
            ['key' => 'lost', 'label' => 'Lost', 'color' => 'red', 'is_final' => 1, 'terminal_type' => 'lost', 'is_active' => 1, 'sort_order' => 8, 'requires_datetime' => 0, 'requires_booking_details' => 0],
            ['key' => 'external_shared', 'label' => 'Shared Externally', 'color' => 'purple', 'is_final' => 0, 'terminal_type' => null, 'is_active' => 1, 'sort_order' => 90, 'requires_datetime' => 0, 'requires_booking_details' => 0],
        ]);
            $this->upsert('activity_types', [
            ['key' => 'call', 'label' => 'Call', 'icon' => '📞', 'requires_outcome' => 1, 'is_system' => 0, 'is_active' => 1, 'sort_order' => 1],
            ['key' => 'whatsapp', 'label' => 'WhatsApp', 'icon' => '💬', 'requires_outcome' => 1, 'is_system' => 0, 'is_active' => 1, 'sort_order' => 2],
            ['key' => 'email', 'label' => 'Email', 'icon' => '✉️', 'requires_outcome' => 1, 'is_system' => 0, 'is_active' => 1, 'sort_order' => 3],
            ['key' => 'meeting', 'label' => 'Meeting', 'icon' => '🤝', 'requires_outcome' => 0, 'is_system' => 0, 'is_active' => 1, 'sort_order' => 4],
            ['key' => 'note', 'label' => 'Note', 'icon' => '📝', 'requires_outcome' => 0, 'is_system' => 0, 'is_active' => 1, 'sort_order' => 5],
            ['key' => 'status_change', 'label' => 'Status Change', 'icon' => '🔄', 'requires_outcome' => 0, 'is_system' => 1, 'is_active' => 1, 'sort_order' => 6],
            ['key' => 'lead_shared', 'label' => 'Lead Shared', 'icon' => '👥', 'requires_outcome' => 0, 'is_system' => 1, 'is_active' => 1, 'sort_order' => 15],
            ['key' => 'lead_reassigned', 'label' => 'Lead Reassigned', 'icon' => '🔄', 'requires_outcome' => 0, 'is_system' => 1, 'is_active' => 1, 'sort_order' => 16],
            ['key' => 'site_visit', 'label' => 'Site Visit', 'icon' => '🏠', 'requires_outcome' => 1, 'is_system' => 0, 'is_active' => 1, 'sort_order' => 20],
            ['key' => 'shared_agent_report', 'label' => 'Shared Agent Report', 'icon' => '👥', 'requires_outcome' => 1, 'is_system' => 0, 'is_active' => 1, 'sort_order' => 100],
            ['key' => 'site_team_report', 'label' => 'Site Team Report', 'icon' => '🏢', 'requires_outcome' => 1, 'is_system' => 0, 'is_active' => 1, 'sort_order' => 101],
            ['key' => 'external_share', 'label' => 'External Share', 'icon' => '📤', 'requires_outcome' => 0, 'is_system' => 1, 'is_active' => 1, 'sort_order' => 200],
        ]);
            $this->upsert('followup_action_types', [
            ['key' => 'post_visit_call', 'label' => 'Post-Visit Follow-up Call', 'is_active' => 1, 'sort_order' => 1],
            ['key' => 'negotiation_followup', 'label' => 'Negotiation Follow-up', 'is_active' => 1, 'sort_order' => 2],
            ['key' => 'thank_you_call', 'label' => 'Thank You Call', 'is_active' => 1, 'sort_order' => 3],
            ['key' => 'reactivation_call', 'label' => 'Re-activation Call', 'is_active' => 1, 'sort_order' => 4],
            ['key' => 'retry_call', 'label' => 'Retry Call', 'is_active' => 1, 'sort_order' => 5],
            ['key' => 'send_details', 'label' => 'Send Details', 'is_active' => 1, 'sort_order' => 6],
            ['key' => 'send_brochure', 'label' => 'Send Brochure & Pricing', 'is_active' => 1, 'sort_order' => 7],
            ['key' => 'confirm_site_visit', 'label' => 'Confirm Site Visit', 'is_active' => 1, 'sort_order' => 8],
            ['key' => 'verify_contact', 'label' => 'Verify Contact', 'is_active' => 1, 'sort_order' => 9],
            ['key' => 'send_budget_options', 'label' => 'Send Budget Options', 'is_active' => 1, 'sort_order' => 10],
            ['key' => 'send_location_opts', 'label' => 'Send Location Options', 'is_active' => 1, 'sort_order' => 11],
            ['key' => 'followup_call', 'label' => 'Follow-up Call', 'is_active' => 1, 'sort_order' => 12],
            ['key' => 'call', 'label' => 'Call', 'is_active' => 1, 'sort_order' => 13],
            ['key' => 'whatsapp_followup', 'label' => 'WhatsApp Follow-up', 'is_active' => 1, 'sort_order' => 14],
            ['key' => 'visit_reminder', 'label' => 'Pre-Visit Confirmation Call', 'is_active' => 1, 'sort_order' => 20],
            ['key' => 'visit_feedback_call', 'label' => 'Post-Visit Feedback Call', 'is_active' => 1, 'sort_order' => 21],
            ['key' => 'visit_outcome_call', 'label' => 'Visit Outcome Call', 'is_active' => 1, 'sort_order' => 22],
            ['key' => 'booking_confirmation', 'label' => 'Booking Confirmation Call', 'is_active' => 1, 'sort_order' => 23],
            ['key' => 'brokerage_followup', 'label' => 'Brokerage Follow-up', 'is_active' => 1, 'sort_order' => 24],
            ['key' => 'check_shared_agent', 'label' => 'Check Shared Agent', 'is_active' => 1, 'sort_order' => 100],
            ['key' => 'check_site_team', 'label' => 'Check Site Team', 'is_active' => 1, 'sort_order' => 101],
        ]);
            $this->upsert('lead_sources', [
            ['key' => 'manual', 'label' => 'Manual', 'is_active' => 1, 'sort_order' => 1],
            ['key' => 'website', 'label' => 'Website', 'is_active' => 1, 'sort_order' => 2],
            ['key' => 'facebook', 'label' => 'Facebook', 'is_active' => 1, 'sort_order' => 3],
            ['key' => 'google', 'label' => 'Google', 'is_active' => 1, 'sort_order' => 4],
            ['key' => 'referral', 'label' => 'Referral', 'is_active' => 1, 'sort_order' => 5],
            ['key' => 'walk_in', 'label' => 'Walk-in', 'is_active' => 1, 'sort_order' => 6],
            ['key' => '99acres', 'label' => '99acres', 'is_active' => 1, 'sort_order' => 7],
            ['key' => 'magicbricks', 'label' => 'MagicBricks', 'is_active' => 1, 'sort_order' => 8],
            ['key' => 'housing', 'label' => 'Housing.com', 'is_active' => 1, 'sort_order' => 9],
            ['key' => 'google_organic', 'label' => 'Google (Organic)', 'is_active' => 1, 'sort_order' => 20],
            ['key' => 'google_ads', 'label' => 'Google Ads (Paid)', 'is_active' => 1, 'sort_order' => 21],
            ['key' => 'facebook_organic', 'label' => 'Facebook (Organic)', 'is_active' => 1, 'sort_order' => 22],
            ['key' => 'facebook_ads', 'label' => 'Facebook Ads (Paid)', 'is_active' => 1, 'sort_order' => 23],
            ['key' => 'instagram_organic', 'label' => 'Instagram (Organic)', 'is_active' => 1, 'sort_order' => 24],
            ['key' => 'instagram_ads', 'label' => 'Instagram Ads (Paid)', 'is_active' => 1, 'sort_order' => 25],
            ['key' => 'bing_organic', 'label' => 'Bing (Organic)', 'is_active' => 1, 'sort_order' => 26],
            ['key' => 'bing_ads', 'label' => 'Bing Ads (Paid)', 'is_active' => 1, 'sort_order' => 27],
            ['key' => 'linkedin_organic', 'label' => 'LinkedIn (Organic)', 'is_active' => 1, 'sort_order' => 28],
            ['key' => 'linkedin_ads', 'label' => 'LinkedIn Ads (Paid)', 'is_active' => 1, 'sort_order' => 29],
            ['key' => 'whatsapp', 'label' => 'WhatsApp', 'is_active' => 1, 'sort_order' => 30],
            ['key' => 'walk_in_organic', 'label' => 'Walk-in', 'is_active' => 1, 'sort_order' => 31],
            ['key' => 'direct', 'label' => 'Direct', 'is_active' => 1, 'sort_order' => 32],
            ['key' => 'website_chat', 'label' => 'Website Chat', 'is_active' => 1, 'sort_order' => 33],
            ['key' => 'whatsapp_waba', 'label' => 'WhatsApp (WABA)', 'is_active' => 1, 'sort_order' => 100],
        ]);
            $this->seedTransitions();
            $this->seedOutcomes();
            $this->upsert('settings', [
            ['key' => 'activity_log_window_minutes', 'value' => '15'],
            ['key' => 'admins_auto_assignable', 'value' => '0'],
            ['key' => 'company_name', 'value' => 'NPO CRM'],
            ['key' => 'contacts_visibility', 'value' => 'telecallers_only'],
            ['key' => 'default_agent_max_daily_leads', 'value' => '10'],
            ['key' => 'default_brokerage_percentage', 'value' => '2'],
            ['key' => 'first_contact_delay_minutes', 'value' => '15'],
            ['key' => 'followup_escalation_hours', 'value' => '4'],
            ['key' => 'followup_work_end', 'value' => '20:00'],
            ['key' => 'followup_work_start', 'value' => '10:30'],
            ['key' => 'followup_working_days', 'value' => '0,1,2,3,4,5,6'],
            ['key' => 'intelligent_engine_enabled', 'value' => '1'],
            ['key' => 'project_routing_strict', 'value' => '1'],
            ['key' => 'unassigned_alert_min_age_minutes', 'value' => '5'],
            ['key' => 'unassigned_alert_repeat_minutes', 'value' => '15'],
            ['key' => 'website_intake_auto_create_project', 'value' => '1'],
            ['key' => 'website_intake_default_source', 'value' => 'website'],
            ['key' => 'website_intake_enabled', 'value' => '1'],
            ['key' => 'website_intake_rate_per_minute', 'value' => '5'],
            ['key' => 'website_intake_require_api_key', 'value' => '0'],
        ]);
        });
    }

    private function seedTransitions(): void
    {
        $ids = DB::table('lead_statuses')->pluck('id', 'key');
        foreach ([
            ['new', 'attempted'],
            ['new', 'lost'],
            ['new', 'external_shared'],
            ['attempted', 'contacted'],
            ['attempted', 'lost'],
            ['contacted', 'visit_scheduled'],
            ['contacted', 'visit_done'],
            ['contacted', 'negotiation'],
            ['contacted', 'booking'],
            ['contacted', 'lost'],
            ['visit_scheduled', 'visit_done'],
            ['visit_scheduled', 'negotiation'],
            ['visit_scheduled', 'booking'],
            ['visit_scheduled', 'lost'],
            ['visit_done', 'negotiation'],
            ['visit_done', 'booking'],
            ['visit_done', 'lost'],
            ['negotiation', 'booking'],
            ['negotiation', 'lost'],
            ['lost', 'new'],
            ['lost', 'contacted'],
            ['external_shared', 'attempted'],
            ['external_shared', 'lost'],
        ] as [$from, $to]) {
            DB::table('lead_status_transitions')->updateOrInsert([
                'from_status_id' => $ids[$from],
                'to_status_id' => $ids[$to],
            ], []);
        }
    }

    private function seedOutcomes(): void
    {
        $actionIds = DB::table('followup_action_types')->pluck('id', 'key');
        $statusIds = DB::table('lead_statuses')->pluck('id', 'key');

        foreach ([
            ['key' => 'interested', 'label' => '✅ Interested', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'send_details', 'next_action_delay_hours' => 2, 'priority' => 'high', 'suggested_status_key' => 'contacted', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 1],
            ['key' => 'asked_details', 'label' => '📄 Asked for details', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'whatsapp_followup', 'next_action_delay_hours' => 1, 'priority' => 'normal', 'suggested_status_key' => 'contacted', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 1, 'is_active' => 1, 'sort_order' => 2],
            ['key' => 'site_visit_scheduled', 'label' => '🏠 Site visit scheduled', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'confirm_site_visit', 'next_action_delay_hours' => 1, 'priority' => 'high', 'suggested_status_key' => 'visit_scheduled', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 1, 'next_action_anchor' => 'visit_before', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 3],
            ['key' => 'negotiating', 'label' => '🤝 Negotiating', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'negotiation_followup', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => 'negotiation', 'context_action_key' => 'negotiation_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 4],
            ['key' => 'call_later', 'label' => '🕒 Call later', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 5],
            ['key' => 'not_answered', 'label' => '📵 Not answered', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 2, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 6],
            ['key' => 'busy', 'label' => '⏳ Busy', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 2, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 7],
            ['key' => 'switched_off', 'label' => '🔌 Switched off', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 8, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 8],
            ['key' => 'not_reachable', 'label' => '📴 Not reachable', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 9],
            ['key' => 'not_interested', 'label' => '❌ Not interested', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 10],
            ['key' => 'visit_confirmed', 'label' => 'Customer confirmed the site visit', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'visit_reminder', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'confirm_site_visit', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'visit_before', 'activity_type_filter' => null, 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 10],
            ['key' => 'reminder_confirmed', 'label' => 'Customer confirmed they are coming', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'visit_feedback_call', 'next_action_delay_hours' => 1, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'visit_reminder', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'visit_after', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 10],
            ['key' => 'wrong_number', 'label' => '⚠️ Wrong number', 'category' => 'negative', 'is_connected' => 0, 'next_action_key' => 'verify_contact', 'next_action_delay_hours' => 24, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 11],
            ['key' => 'budget_issue', 'label' => '💰 Budget issue', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'send_budget_options', 'next_action_delay_hours' => 48, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 12],
            ['key' => 'location_issue', 'label' => '📍 Location issue', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'send_location_opts', 'next_action_delay_hours' => 72, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 13],
            ['key' => 'already_bought', 'label' => '🏁 Already bought', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 4320, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 14],
            ['key' => 'visit_reschedule_requested', 'label' => 'Customer asked to reschedule', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'confirm_site_visit', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'confirm_site_visit', 'contact_status_key' => null, 'requires_site_visit_datetime' => 1, 'next_action_anchor' => 'now', 'activity_type_filter' => null, 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 20],
            ['key' => 'reminder_reschedule_requested', 'label' => 'Customer asked to change the visit time', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'confirm_site_visit', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'visit_reminder', 'contact_status_key' => null, 'requires_site_visit_datetime' => 1, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 20],
            ['key' => 'booking_confirmed', 'label' => '🎉 Booking Confirmed', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'thank_you_call', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => 'booking', 'context_action_key' => 'booking_confirmation', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 25],
            ['key' => 'booking_postponed', 'label' => '📅 Booking Postponed', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 24, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'booking_confirmation', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 26],
            ['key' => 'booking_payment_issue', 'label' => '💰 Payment Issue', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'booking_confirmation', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 27],
            ['key' => 'booking_backed_out', 'label' => '❌ Customer Backed Out', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => 'booking_confirmation', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 28],
            ['key' => 'booking_needs_more_time', 'label' => '⏳ Needs More Time to Decide', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 72, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'booking_confirmation', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 29],
            ['key' => 'visit_cancelled', 'label' => 'Customer cancelled the site visit', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'confirm_site_visit', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => null, 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 30],
            ['key' => 'reminder_cancelled', 'label' => 'Customer cancelled the visit', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'visit_reminder', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 30],
            ['key' => 'visit_booked_spot', 'label' => '🎉 Booked on the spot', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'booking_confirmation', 'next_action_delay_hours' => 4, 'priority' => 'high', 'suggested_status_key' => 'booking', 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_visit', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 31],
            ['key' => 'visit_interested', 'label' => '👍 Interested, will decide', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'visit_feedback_call', 'next_action_delay_hours' => 4, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_visit', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 32],
            ['key' => 'visit_needs_family', 'label' => '👨‍👩‍👧 Needs family approval', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'visit_feedback_call', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_visit', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 33],
            ['key' => 'visit_wants_negotiate', 'label' => '💰 Wants to negotiate price', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'negotiation_followup', 'next_action_delay_hours' => 4, 'priority' => 'high', 'suggested_status_key' => 'negotiation', 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_visit', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 34],
            ['key' => 'visit_wants_other_project', 'label' => '🏗️ Wants to see other project', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'send_details', 'next_action_delay_hours' => 24, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_visit', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 35],
            ['key' => 'visit_not_interested', 'label' => '❌ Not interested after visit', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_visit', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 36],
            ['key' => 'visit_no_show', 'label' => '🚫 Customer did not show up', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'visit_reminder', 'next_action_delay_hours' => 2, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_visit', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 37],
            ['key' => 'thanks_happy', 'label' => '😊 Customer thanked, happy', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => null, 'next_action_delay_hours' => 24, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'thank_you_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 40],
            ['key' => 'visit_not_reachable', 'label' => 'Could not reach customer for confirmation', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'confirm_site_visit', 'next_action_delay_hours' => 4, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'confirm_site_visit', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => null, 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 40],
            ['key' => 'reminder_no_contact', 'label' => 'Could not reach customer for the reminder', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'visit_reminder', 'next_action_delay_hours' => 2, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'visit_reminder', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 40],
            ['key' => 'thanks_referral_won', 'label' => '⭐ Referral received', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => null, 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'thank_you_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 41],
            ['key' => 'thanks_referral_promised', 'label' => '💬 Referral promised', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 168, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'thank_you_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 42],
            ['key' => 'brok_received_full', 'label' => '✅ Full brokerage received', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => null, 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'brokerage_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 50],
            ['key' => 'wa_sent_details', 'label' => '📤 Sent details on WhatsApp', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'whatsapp_followup', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => 'contacted', 'context_action_key' => 'whatsapp_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 60],
            ['key' => 'wa_replied_positive', 'label' => '✅ Replied positively', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 1, 'priority' => 'high', 'suggested_status_key' => 'contacted', 'context_action_key' => 'whatsapp_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 61],
            ['key' => 'wa_read_no_reply', 'label' => '👀 Read, no reply', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'whatsapp_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 62],
            ['key' => 'wa_delivered_awaiting', 'label' => '📨 Delivered, awaiting reply', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'whatsapp_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 63],
            ['key' => 'wa_not_interested', 'label' => '❌ Not interested', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => 'whatsapp_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 64],
            ['key' => 'wa_blocked', 'label' => '🚫 Blocked / reported', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 4320, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => 'whatsapp_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 65],
            ['key' => 'invalid_number', 'label' => '🚫 Invalid number', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'verify_contact', 'next_action_delay_hours' => 24, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 66],
            ['key' => 'details_sent', 'label' => 'Requested details were sent', 'category' => 'positive', 'is_connected' => 0, 'next_action_key' => 'whatsapp_followup', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'send_details', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 90],
            ['key' => 'details_not_sent', 'label' => 'Details could not be sent', 'category' => 'negative', 'is_connected' => 0, 'next_action_key' => 'send_details', 'next_action_delay_hours' => 2, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'send_details', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 91],
            ['key' => 'brochure_sent', 'label' => 'Brochure was sent', 'category' => 'positive', 'is_connected' => 0, 'next_action_key' => 'whatsapp_followup', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'send_brochure', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 92],
            ['key' => 'brochure_not_sent', 'label' => 'Brochure could not be sent', 'category' => 'negative', 'is_connected' => 0, 'next_action_key' => 'send_brochure', 'next_action_delay_hours' => 2, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'send_brochure', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 93],
            ['key' => 'budget_options_sent', 'label' => 'Budget options were sent', 'category' => 'positive', 'is_connected' => 0, 'next_action_key' => 'whatsapp_followup', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'send_budget_options', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 94],
            ['key' => 'location_options_sent', 'label' => 'Location options were sent', 'category' => 'positive', 'is_connected' => 0, 'next_action_key' => 'whatsapp_followup', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'send_location_opts', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 95],
            ['key' => 'customer_requested_call', 'label' => 'Customer asked to discuss by call', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 1, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'send_details', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 96],
            ['key' => 'shared_agent_contacted', 'label' => 'Co-agent reached the customer', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => null, 'next_action_delay_hours' => 0, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'check_shared_agent', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'shared_agent_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 100],
            ['key' => 'shared_agent_visit_set', 'label' => 'Co-agent set a site visit', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'confirm_site_visit', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => 'visit_scheduled', 'context_action_key' => 'check_shared_agent', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'shared_agent_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 101],
            ['key' => 'shared_agent_booked', 'label' => 'Co-agent closed the booking', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'thank_you_call', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => 'booking', 'context_action_key' => 'check_shared_agent', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'shared_agent_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 102],
            ['key' => 'shared_agent_no_response', 'label' => 'Co-agent hasn\'t updated yet', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'check_shared_agent', 'next_action_delay_hours' => 24, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'check_shared_agent', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'shared_agent_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 103],
            ['key' => 'shared_agent_lost', 'label' => 'Co-agent reports the lead is lost', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => 'check_shared_agent', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'shared_agent_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 104],
            ['key' => 'site_team_call_done', 'label' => 'Site team made first call', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'check_site_team', 'next_action_delay_hours' => 48, 'priority' => 'high', 'suggested_status_key' => 'contacted', 'context_action_key' => 'check_site_team', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_team_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 110],
            ['key' => 'site_team_visit_done', 'label' => 'Site team completed the visit', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'check_site_team', 'next_action_delay_hours' => 48, 'priority' => 'high', 'suggested_status_key' => 'visit_done', 'context_action_key' => 'check_site_team', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_team_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 111],
            ['key' => 'site_team_negotiating', 'label' => 'Site team is negotiating', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'negotiation_followup', 'next_action_delay_hours' => 48, 'priority' => 'high', 'suggested_status_key' => 'negotiation', 'context_action_key' => 'check_site_team', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_team_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 112],
            ['key' => 'site_team_booked', 'label' => 'Site team closed the booking', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'thank_you_call', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => 'booking', 'context_action_key' => 'check_site_team', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_team_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 113],
            ['key' => 'site_team_lost', 'label' => 'Site team reports lost', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => 'check_site_team', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_team_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 114],
            ['key' => 'site_team_no_report', 'label' => 'No report from site team yet', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'check_site_team', 'next_action_delay_hours' => 72, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'check_site_team', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_team_report', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 115],
            ['key' => 'customer_hung_up', 'label' => '📵 Customer cut the call', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 200],
            ['key' => 'family_member_answered', 'label' => '👨 Family member answered', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 201],
            ['key' => 'number_switched_off_perm', 'label' => '🔕 Number permanently off', 'category' => 'negative', 'is_connected' => 0, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 4320, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 202],
            ['key' => 'network_issue', 'label' => '📶 Network issue', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 2, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 203],
            ['key' => 'wants_rental', 'label' => '🏠 Wants rental, not purchase', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 4320, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 204],
            ['key' => 'wants_ready_possession', 'label' => '🏁 Wants ready possession', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'send_details', 'next_action_delay_hours' => 48, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 205],
            ['key' => 'wants_resale', 'label' => '🏚️ Wants resale property', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 4320, 'priority' => 'normal', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 206],
            ['key' => 'loan_denied', 'label' => '❌ Loan rejected', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 4320, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => 'negotiation_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 207],
            ['key' => 'loan_in_process', 'label' => '🏦 Loan in process', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 48, 'priority' => 'high', 'suggested_status_key' => 'negotiation', 'context_action_key' => 'negotiation_followup', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 208],
            ['key' => 'consult_family', 'label' => '👨‍👩‍👧 Will consult family/astrologer', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 72, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 209],
            ['key' => 'not_ready_to_buy', 'label' => '⏸️ Not ready to buy yet', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 2160, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 210],
            ['key' => 'site_visit_cancelled', 'label' => '❌ Cancelled the visit', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 24, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 211],
            ['key' => 'wants_second_visit', 'label' => '🔁 Wants to revisit', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'confirm_site_visit', 'next_action_delay_hours' => 4, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 212],
            ['key' => 'language_barrier', 'label' => '🗣️ Language barrier', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 250],
            ['key' => 'requested_whatsapp_only', 'label' => '💬 Wants WhatsApp only', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'whatsapp_followup', 'next_action_delay_hours' => 24, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 251],
            ['key' => 'customer_will_call_back', 'label' => '🔄 Customer will call back', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 24, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 252],
            ['key' => 'deal_closed_elsewhere', 'label' => '🤷 Bought from someone else', 'category' => 'negative', 'is_connected' => 1, 'next_action_key' => 'reactivation_call', 'next_action_delay_hours' => 4320, 'priority' => 'low', 'suggested_status_key' => 'lost', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 253],
            ['key' => 'site_visit_arrived_late', 'label' => '🕐 Arrived late for visit', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'visit_feedback_call', 'next_action_delay_hours' => 4, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 254],
            ['key' => 'site_visit_with_family', 'label' => '👨‍👩‍👧 Visited with family', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'visit_feedback_call', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => 'visit_feedback_call', 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 255],
            ['key' => 'booking_kyc_pending', 'label' => '📋 Booking KYC pending', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 48, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 256],
            ['key' => 'booking_registration_done', 'label' => '📝 Booking registered', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'thank_you_call', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 257],
            ['key' => 'wants_emi_options', 'label' => '💳 Asked for EMI options', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'send_details', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 300],
            ['key' => 'wants_possession_date', 'label' => '📅 Asked for possession date', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'send_details', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 301],
            ['key' => 'investor_looking_rental_yield', 'label' => '📈 Investor — rental yield focus', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'send_details', 'next_action_delay_hours' => 48, 'priority' => 'normal', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 302],
            ['key' => 'booking_amount_paid', 'label' => '💵 Token amount paid', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'booking_confirmation', 'next_action_delay_hours' => 4, 'priority' => 'high', 'suggested_status_key' => 'booking', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp,email', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 303],
            ['key' => 'site_visit_with_kids', 'label' => '👶 Visited with children', 'category' => 'positive', 'is_connected' => 1, 'next_action_key' => 'visit_feedback_call', 'next_action_delay_hours' => 24, 'priority' => 'high', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'site_visit', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 304],
            ['key' => 'referred_but_not_responding', 'label' => '📵 Referral not reachable', 'category' => 'neutral', 'is_connected' => 0, 'next_action_key' => 'retry_call', 'next_action_delay_hours' => 24, 'priority' => 'low', 'suggested_status_key' => null, 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 305],
            ['key' => 'already_visited_project', 'label' => '👣 Already Visited Enquired Project', 'category' => 'neutral', 'is_connected' => 1, 'next_action_key' => 'followup_call', 'next_action_delay_hours' => 24, 'priority' => 'normal', 'suggested_status_key' => 'contacted', 'context_action_key' => null, 'contact_status_key' => null, 'requires_site_visit_datetime' => 0, 'next_action_anchor' => 'now', 'activity_type_filter' => 'call,whatsapp', 'prompts_whatsapp_send' => 0, 'is_active' => 1, 'sort_order' => 500],
        ] as $row) {
            $nextActionKey = $row['next_action_key'];
            $suggestedStatusKey = $row['suggested_status_key'];
            unset($row['next_action_key'], $row['suggested_status_key']);

            $row['next_action_type_id'] = $nextActionKey !== null ? $actionIds[$nextActionKey] : null;
            $row['suggested_status_id'] = $suggestedStatusKey !== null ? $statusIds[$suggestedStatusKey] : null;
            DB::table('call_outcomes')->updateOrInsert(['key' => $row['key']], $row);
        }
    }

    private function upsert(string $table, array $rows): void
    {
        foreach ($rows as $row) {
            DB::table($table)->updateOrInsert(['key' => $row['key']], $row);
        }
    }
}
