@extends('layouts.app')
@section('title','Booking Financial Engine — NPO CRM')
@section('content')
@php $money=fn($v)=>inr($v,0); $canManage=true; $sim=session('simulation'); $payload=$importBatch?->mapping_json ?: []; @endphp
<style>
.bf{max-width:1500px;margin:0 auto;padding:14px}.bf-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.bf-tabs{display:flex;gap:7px;overflow:auto;margin:12px 0;position:sticky;top:0;z-index:20;padding:4px 0;background:#fff}.bf-tabs a{white-space:nowrap;padding:9px 12px;border:1px solid #ddd;border-radius:9px;text-decoration:none;color:inherit}.bf-tabs a.active{font-weight:800;border-color:#2563eb;background:#eef5ff}.bf-guidebar{display:flex;gap:8px;flex-wrap:wrap;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:10px;margin:10px 0}.bf-guidebar a{font-size:12px;text-decoration:none;border:1px solid #cbd5e1;border-radius:999px;padding:7px 10px;color:inherit;background:#fff}.bf-sectionnav{display:flex;gap:7px;overflow:auto;position:sticky;top:49px;z-index:19;background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:7px;margin-bottom:12px}.bf-sectionnav a{white-space:nowrap;text-decoration:none;font-size:12px;font-weight:700;padding:7px 10px;border-radius:8px;background:#f8fafc;color:inherit}.bf-card{background:#fff;border:1px solid #ddd;border-radius:12px;padding:14px;margin-bottom:12px}.bf-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.bf-form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.bf-form .full{grid-column:1/-1}.bf-form label{font-size:12px;font-weight:700;display:block;margin-bottom:4px}.bf-form input,.bf-form select,.bf-form textarea{width:100%;box-sizing:border-box;padding:8px;border:1px solid #d0d5dd;border-radius:8px}.bf-btn{border:0;border-radius:8px;padding:8px 11px;background:#2563eb;color:#fff;cursor:pointer;text-decoration:none;display:inline-block}.bf-btn.warn{background:#b54708}.bf-btn.gray{background:#667085}.bf-note{font-size:12px;color:#667085;line-height:1.5}.bf-scroll{overflow:auto}.bf-table{width:100%;border-collapse:collapse}.bf-table th,.bf-table td{padding:8px;border-bottom:1px solid #eee;text-align:left;font-size:12px;vertical-align:top}.bf-table th{white-space:nowrap}.bf-num{text-align:right}.bf-success{background:#ecfdf3;border:1px solid #abefc6;padding:10px;border-radius:9px;margin-bottom:10px}.bf-error{background:#fff3f2;border:1px solid #fecdca;padding:10px;border-radius:9px;margin-bottom:10px}.bf-kpi{font-size:23px;font-weight:800}.bf-label{font-size:12px;color:#667085}@media(max-width:900px){.bf-grid,.bf-form{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.bf{padding:9px}.bf-tabs{top:0}.bf-sectionnav{top:48px}.bf-head{display:block}.bf-grid,.bf-form{grid-template-columns:1fr}.bf-form .full{grid-column:auto}.bf-btn{width:100%;box-sizing:border-box;text-align:center;margin-top:3px}}
</style>
<div class="bf">
 <div class="bf-head"><div><h1 style="margin:0">💼 Booking Financial Engine</h1><div class="bf-note">Booking → Brokerage Agreement → Brokerage Calculation → Payables → Net Brokerage → Employee Incentive Allocations → Collections/Payouts.</div></div><a class="bf-btn gray" href="/admin/incentives">← Incentives</a></div>
 @if(session('success'))<div class="bf-success">{{session('success')}}</div>@endif
 @if(session('error'))<div class="bf-error">{{session('error')}}</div>@endif
 @if($errors->any())<div class="bf-error"><strong>Please correct:</strong><ul>@foreach($errors->all() as $e)<li>{{$e}}</li>@endforeach</ul></div>@endif
 <nav class="bf-tabs">@foreach(['bookings'=>'📒 Bookings & Workflow','rules'=>'⚙️ Brokerage & Financial Rules','payables'=>'💸 Payables','salary'=>'👤 People & Salary','import'=>'📥 Imports','simulation'=>'🧪 What-if Simulation'] as $k=>$label)<a class="{{$tab===$k?'active':''}}" href="/admin/booking-finance?tab={{$k}}">{{$label}}</a>@endforeach</nav>
 <div class="bf-guidebar"><strong style="font-size:12px;padding:7px 4px">What do you want to do?</strong><a href="/admin/booking-finance?tab=bookings#booking-register">Find / enter a booking</a><a href="/admin/booking-finance?tab=rules">Set brokerage rules</a><a href="/admin/booking-finance?tab=payables">Set payable types</a><a href="/admin/booking-finance?tab=salary">Manage salary history</a><a href="/admin/booking-finance?tab=import">Import bookings</a><a href="/admin/booking-finance?tab=simulation">Test a rule</a><a href="/incentive-guide.html">📘 Help / Guide</a></div>

 @if($tab==='bookings')
 <div class="bf-sectionnav"><a href="#booking-entry">① Booking entry</a><a href="#booking-register">② Booking register</a>@if($editBooking)<a href="#booking-money">③ Brokerage / NB</a><a href="#booking-allocations">④ Employee incentive</a><a href="#booking-payables">⑤ Payables</a>@endif</div>
 <div class="bf-card"><h3>What happens to a booking?</h3><p class="bf-note"><strong>Live CRM:</strong> when an existing Lead reaches Booking, the CRM keeps its existing booking workflow. A financial record is created from the booking and follows the existing Booking Control approval. <strong>Historical/manual/imported:</strong> create a draft here, review the calculated brokerage/payables/NB, then Submit → Authorize. Authorization creates the authoritative incentive deal snapshot.</p></div>
 <div class="bf-card">
  <h3 id="booking-entry">{{ $editBooking?'Edit booking financial record #'.$editBooking->id:'＋ Add historical / manual booking' }}</h3>
  <form method="POST" action="/admin/booking-finance/bookings{{ $editBooking?'/'.$editBooking->id:'' }}" class="bf-form">@csrf
   <div><label>Source</label><select name="source_type"><option value="historical">Historical</option><option value="manual">Manual / Exception</option><option value="imported">Imported</option></select></div>
   <div><label>Lead ID (live booking only)</label><input name="lead_id" value="{{$editBooking?->lead_id}}"></div><div><label>Booking date</label><input type="date" name="booking_date" required value="{{$editBooking?->booking_date?->format('Y-m-d') ?: now()->format('Y-m-d')}}"></div><div><label>Booking value ₹</label><input type="number" step="0.01" name="booking_amount" required value="{{$editBooking?->booking_amount}}"></div>
   <div><label>Customer name</label><input name="customer_name" required value="{{$editBooking?->customer_name_snapshot}}"></div><div><label>Phone</label><input name="customer_phone" value="{{$editBooking?->customer_phone_snapshot}}"></div><div><label>Project ID</label><input name="project_id" value="{{$editBooking?->project_id}}"></div><div><label>Project name</label><input name="project_name" value="{{$editBooking?->project_name_snapshot}}"></div>
   <div><label>Builder</label><input name="builder_name" value="{{$editBooking?->builder_name}}"></div><div><label>Unit type</label><input name="unit_type" value="{{$editBooking?->unit_type}}"></div><div><label>Unit / Flat</label><input name="booking_unit" value="{{$editBooking?->booking_unit}}"></div><div><label>Source reference</label><input name="source_reference" value="{{$editBooking?->source_reference}}"></div>
   <div><label>Area sqft</label><input type="number" step="0.01" name="property_area_sqft" value="{{$editBooking?->property_area_sqft}}"></div><div><label>Rate / sqft</label><input type="number" step="0.01" name="rate_per_sqft" value="{{$editBooking?->rate_per_sqft}}"></div><div class="full"><button class="bf-btn">Save draft & calculate</button></div>
  </form>
 </div>
 <div class="bf-card" id="booking-register"><h3>Booking register</h3><div class="bf-scroll"><table class="bf-table"><tr><th>ID</th><th>Customer / Project</th><th>Date</th><th class="bf-num">Booking</th><th class="bf-num">Brokerage</th><th class="bf-num">NB</th><th>Status</th><th>Actions</th></tr>@foreach($bookings as $b)<tr><td>#{{$b->id}}</td><td><strong>{{$b->customer_name_snapshot}}</strong><br>{{$b->project_name_snapshot}}<br><span class="bf-note">{{$b->builder_name}}</span></td><td>{{$b->booking_date?->format('d M Y')}}</td><td class="bf-num">{{$money($b->booking_amount)}}</td><td class="bf-num">{{$money($b->brokerage_gross)}}</td><td class="bf-num"><strong>{{$money($b->net_brokerage)}}</strong></td><td>{{$b->status}}</td><td><a class="bf-btn gray" href="/admin/booking-finance?tab=bookings&edit_booking={{$b->id}}">Open</a>@if(in_array($b->status,['draft','submitted']))<form method="POST" action="/admin/booking-finance/bookings/{{$b->id}}/submit" style="display:inline">@csrf<button class="bf-btn">Submit</button></form>@endif @if($b->status==='submitted')<form method="POST" action="/admin/booking-finance/bookings/{{$b->id}}/authorize" style="display:inline" onsubmit="return confirm('Authorize this booking financial record?')">@csrf<button class="bf-btn warn">Authorize</button></form>@endif</td></tr>@endforeach</table></div>{{$bookings->links()}}</div>
 @if($editBooking)
 <div class="bf-grid" id="booking-money"><div class="bf-card"><div class="bf-label">Brokerage</div><div class="bf-kpi">{{$money($editBooking->brokerage_gross)}}</div><div class="bf-note">Rule #{{$editBooking->brokerage_rule_id ?: 'legacy/default'}}</div></div><div class="bf-card"><div class="bf-label">NB after deductions</div><div class="bf-kpi">{{$money($editBooking->net_brokerage)}}</div></div><div class="bf-card"><div class="bf-label">Payables reducing NB</div><div class="bf-kpi">{{$money($editBooking->payable_deduction_total)}}</div></div><div class="bf-card"><div class="bf-label">Financial status</div><div class="bf-kpi" style="font-size:18px">{{$editBooking->status}}</div></div></div>
 <div class="bf-card" id="booking-allocations"><h3>Employee incentive allocations</h3><form method="POST" action="/admin/booking-finance/bookings/{{$editBooking->id}}/allocations" class="bf-form">@csrf<div><label>Employee</label><select name="agent_id" required>@foreach($agents as $a)<option value="{{$a->id}}">{{$a->user?->name}}</option>@endforeach</select></div><div><label>Allocation type</label><select name="allocation_type"><option value="percentage">Percentage</option><option value="fixed">Fixed</option></select></div><div><label>Base</label><select name="base_type"><option value="net_brokerage">Net Brokerage</option><option value="brokerage_gross">Gross Brokerage</option><option value="booking_value">Booking Value</option></select></div><div><label>Rate %</label><input name="rate" type="number" step="0.001"></div><div><label>Fixed ₹</label><input name="fixed_amount" type="number" step="0.01"></div><div class="full"><button class="bf-btn">Add allocation</button></div></form><div class="bf-scroll"><table class="bf-table"><tr><th>Employee</th><th>Base</th><th>Rate</th><th>Calculated incentive</th><th>Rule</th></tr>@foreach($editBooking->allocations as $a)<tr><td>{{$a->agent?->user?->name}}</td><td>{{$a->base_type}}</td><td>{{ $a->allocation_type==='fixed' ? $money($a->fixed_amount) : number_format($a->rate,3).'%' }}</td><td>{{$money($a->calculated_amount)}}</td><td>#{{$a->incentive_rule_id ?: 'manual'}}</td></tr>@endforeach</table></div></div>
 <div class="bf-card" id="booking-payables"><h3>Booking payables</h3><form method="POST" action="/admin/booking-finance/bookings/{{$editBooking->id}}/payables" class="bf-form">@csrf<div><label>Type</label><select name="payable_type_id"><option value="">Custom</option>@foreach($payableTypes as $t)<option value="{{$t->id}}">{{$t->name}} {{ $t->affects_net_brokerage?'(deducts NB)':''}}</option>@endforeach</select></div><div><label>Payee</label><input name="payee_name" required></div><div><label>Amount ₹</label><input name="amount" type="number" step="0.01" required></div><div><label>Due date</label><input name="due_date" type="date"></div><div><label>Deduct from NB?</label><select name="affects_net_brokerage"><option value="0">No</option><option value="1">Yes</option></select></div><div class="full"><button class="bf-btn">Add payable</button></div></form><div class="bf-scroll"><table class="bf-table"><tr><th>Type</th><th>Payee</th><th>Amount</th><th>NB deduction</th><th>Status</th><th>Paid</th></tr>@foreach($editBooking->payables as $p)<tr><td>{{$p->payable_type_name_snapshot}}</td><td>{{$p->payee_name}}</td><td>{{$money($p->amount)}}</td><td>{{$p->affects_net_brokerage?'Yes':'No'}}</td><td>{{$p->status}}</td><td>{{$money($p->payments->sum('amount'))}}</td></tr>@endforeach</table></div></div>
 @endif
 @endif

 @if($tab==='rules')
 <div class="bf-card"><h3>Rule builder</h3><p class="bf-note">Create effective-dated versions. Combine scope + conditions. For “builder 1–5 bookings = 2%, 6+ = 2.5%”, create two brokerage rules with the same builder/effective dates and booking-sequence ranges. For monthly changes, create new effective-date versions; historical bookings retain their rule snapshot.</p><form method="POST" action="/admin/booking-finance/rules" class="bf-form">@csrf
 <div><label>Rule group</label><select name="rule_group"><option value="brokerage">Brokerage</option><option value="incentive">Employee Incentive</option><option value="payable">Payable</option></select></div><div><label>Name</label><input name="name" required></div><div><label>Scope</label><select name="scope_type"><option value="global">Global</option><option value="builder">Builder</option><option value="project">Project</option><option value="agent">Employee</option></select></div><div><label>Scope value</label><input name="scope_value"></div>
 <div><label>Priority</label><input name="priority" type="number" value="100"></div><div><label>Effective from</label><input name="effective_from" type="date" value="{{now()->format('Y-m-d')}}" required></div><div><label>Effective to</label><input name="effective_to" type="date"></div><div><label>Calculation</label><select name="calculation_type"><option value="percentage">Percentage</option><option value="fixed">Fixed</option></select></div><div><label>Base</label><select name="base_type"><option value="booking_value">Booking Value</option><option value="brokerage_gross">Gross Brokerage</option><option value="net_brokerage">Net Brokerage</option><option value="incentive_pool">Incentive Pool</option></select></div><div><label>Rate %</label><input name="rate" type="number" step="0.001"></div><div><label>Fixed ₹</label><input name="fixed_amount" type="number" step="0.01"></div><div><label>Builder condition</label><input name="builder_name"></div><div><label>Project ID condition</label><input name="project_id" type="number"></div><div><label>Booking value min</label><input name="booking_value_min" type="number" step="0.01"></div><div><label>Booking value max</label><input name="booking_value_max" type="number" step="0.01"></div><div><label>Booking sequence min</label><input name="sequence_min" type="number"></div><div><label>Booking sequence max</label><input name="sequence_max" type="number"></div><div><label>Month (1–12)</label><input name="month" type="number" min="1" max="12"></div><div><label>Counter scope</label><select name="counter_scope"><option value="global">Global</option><option value="builder">Builder</option><option value="project">Project</option><option value="agent">Employee</option></select></div><div><label>Counter period</label><select name="counter_period"><option value="month">Month</option><option value="quarter">Quarter</option><option value="year">Year</option><option value="lifetime">Lifetime</option></select></div><div class="full"><label>Description</label><textarea name="description" rows="2"></textarea></div><div class="full"><button class="bf-btn">Create rule version</button></div></form></div>
 <div class="bf-card"><h3>Active rule catalogue</h3><div class="bf-scroll"><table class="bf-table"><tr><th>Group</th><th>Name / Scope</th><th>Effective</th><th>Calc</th><th>Conditions</th><th>Version</th></tr>@foreach($rules as $r)<tr><td>{{$r->rule_group}}</td><td><strong>{{$r->name}}</strong><br>{{$r->scope_type}}: {{$r->scope_value ?: '—'}}</td><td>{{$r->effective_from?->format('d M Y')}} → {{$r->effective_to?->format('d M Y') ?: 'open'}}</td><td>{{$r->calculation_type}} {{ $r->rate!==null?number_format($r->rate,3).'%' : $money($r->fixed_amount) }} / {{$r->base_type}}</td><td><pre style="white-space:pre-wrap;margin:0">{{json_encode($r->conditions_json,JSON_PRETTY_PRINT)}}</pre></td><td>v{{$r->version}}</td></tr>@endforeach</table></div>{{$rules->links()}}</div>
 @endif

 @if($tab==='payables')
 <div class="bf-card"><h3>Payable catalogue — Super Admin controlled</h3><p class="bf-note">Add new payable types without code. Existing booking payables keep a name/category snapshot. Never delete financial history; deactivate a type instead.</p><form method="POST" action="/admin/booking-finance/payable-types" class="bf-form">@csrf<div><label>Name</label><input name="name" required></div><div><label>Code</label><input name="code" required></div><div><label>Category</label><input name="category" value="other"></div><div><label>Calculation</label><select name="calculation_type"><option value="manual">Manual</option><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select></div><div><label>Base</label><input name="base_type" value="booking_value"></div><div><label>Default value/rate</label><input name="default_value" type="number" step="0.001"></div><div><label>Deduct from NB?</label><select name="affects_net_brokerage"><option value="0">No</option><option value="1">Yes</option></select></div><div><label>Requires approval?</label><select name="requires_approval"><option value="0">No</option><option value="1">Yes</option></select></div><div class="full"><textarea name="description" rows="2" placeholder="What is this payable for?"></textarea></div><div class="full"><button class="bf-btn">Add payable type</button></div></form><table class="bf-table"><tr><th>Name</th><th>Code</th><th>Category</th><th>Default</th><th>Deduct NB</th><th>Approval</th><th>Active</th></tr>@foreach($payableTypes as $t)<tr><td>{{$t->name}}</td><td>{{$t->code}}</td><td>{{$t->category}}</td><td>{{$t->default_value}}</td><td>{{$t->affects_net_brokerage?'Yes':'No'}}</td><td>{{$t->requires_approval?'Yes':'No'}}</td><td>{{$t->active?'Yes':'No'}}</td></tr>@endforeach</table></div>
 @endif

 @if($tab==='salary')
 <div class="bf-card"><h3>Salary history</h3><p class="bf-note">Do not overwrite history. Add an effective-dated salary version. Quarterly incentive calculations use the salary applicable to each eligible month and calculate the period's average monthly salary dynamically.</p><table class="bf-table"><tr><th>Employee</th><th>Effective from</th><th>To</th><th>Monthly salary</th><th>Reason</th></tr>@foreach($salaryRows as $s)<tr><td>{{$s->employee_name}}</td><td>{{$s->effective_from}}</td><td>{{$s->effective_to ?: 'current'}}</td><td>{{$money($s->monthly_salary)}}</td><td>{{$s->reason}}</td></tr>@endforeach</table>{{$salaryRows->links()}}</div>
 <div class="bf-card"><h3>Add salary version</h3><form method="POST" action="/admin/booking-finance/salary/0" class="bf-form">@csrf<div><label>Employee</label><select name="agent_id" required><option value="">Select employee</option>@foreach($agents as $a)<option value="{{$a->id}}">{{$a->user?->name}} (#{{$a->id}})</option>@endforeach</select></div><div><label>Effective from</label><input name="effective_from" type="date" required></div><div><label>Effective to</label><input name="effective_to" type="date"></div><div><label>Monthly salary</label><input name="monthly_salary" type="number" step="0.01" required></div><div class="full"><label>Reason</label><input name="reason"></div><div class="full"><button class="bf-btn">Save salary version</button></div></form></div>
 @endif

 @if($tab==='import')
 <div class="bf-card"><h3>CSV / XLSX booking import</h3><p class="bf-note">Import creates <strong>draft</strong> booking records only. It does not silently authorize financials. Preview validates required fields and detects duplicates by source reference or customer phone + booking date + amount. Each batch remains traceable.</p><form method="POST" action="/admin/booking-finance/import/preview" enctype="multipart/form-data" class="bf-form">@csrf<div class="full"><label>CSV or XLSX</label><input type="file" name="file" accept=".csv,.xlsx" required></div><div class="full"><button class="bf-btn">Preview import</button></div></form></div>
 @if($importBatch)<div class="bf-card"><h3>Import batch #{{$importBatch->id}}</h3><p class="bf-note">{{$importBatch->file_name}} · total {{$importBatch->total_rows}} · valid {{$importBatch->valid_rows}} · invalid {{$importBatch->invalid_rows}} · duplicates {{$importBatch->duplicate_rows}}</p><div class="bf-scroll"><table class="bf-table"><tr><th>Customer</th><th>Project</th><th>Date</th><th>Amount</th><th>Result</th></tr>@foreach(($payload['rows']??[]) as $r)<tr><td>{{$r['mapped']['customer_name']??''}}</td><td>{{$r['mapped']['project_name']??''}}</td><td>{{$r['mapped']['booking_date']??''}}</td><td>{{$r['mapped']['booking_amount']??''}}</td><td>{{$r['valid']?'Valid':'Invalid'}} @if($r['duplicate']) / Duplicate @endif</td></tr>@endforeach</table></div><form method="POST" action="/admin/booking-finance/import/{{$importBatch->id}}/commit" onsubmit="return confirm('Create all valid non-duplicate rows as booking drafts?')">@csrf<button class="bf-btn">Commit valid rows as drafts</button></form></div>@endif
 @endif

 @if($tab==='simulation')
 <div class="bf-card"><h3>Booking rule simulation</h3><p class="bf-note">What-if only. It never creates a booking, incentive deal, collection or payable.</p><form method="POST" action="/admin/booking-finance/simulate" class="bf-form">@csrf<div><label>Date</label><input type="date" name="booking_date" value="{{now()->format('Y-m-d')}}"></div><div><label>Booking value</label><input type="number" name="booking_amount" step="0.01" value="10000000"></div><div><label>Project ID</label><input name="project_id"></div><div><label>Project name</label><input name="project_name"></div><div><label>Builder</label><input name="builder_name"></div><div class="full"><button class="bf-btn">Run simulation</button></div></form>@if($sim)<div class="bf-card"><h3>Simulation result</h3><div class="bf-grid"><div><div class="bf-label">Brokerage</div><div class="bf-kpi">{{$money($sim['brokerage'])}}</div></div><div><div class="bf-label">Rule</div><div>{{$sim['rule']?->name ?: 'Legacy/default'}}</div></div></div><pre style="white-space:pre-wrap">{{json_encode($sim['components'],JSON_PRETTY_PRINT)}}</pre></div>@endif</div>
 @endif
</div>
@endsection
